import {
  Box,
  Card,
  CardMedia,
  CircularProgress,
  Skeleton,
  Stack,
  Typography,
} from "@mui/material";
import CardCheckoutProduct from "dh-marvel/components/card-checkout-product/card-checkout-product";
import CardComponent from "dh-marvel/components/card/card.component";
import StepperForm from "dh-marvel/components/forms/stepper-form.component";
import LayoutCheckout from "dh-marvel/components/layouts/layout-checkout";
import { getComicsById } from "dh-marvel/services/comic/comic.service";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IComic, IComicResponse } from "types/IComic.type";

const Checkout: NextPage = () => {
  const router = useRouter();
  const { comic } = router.query;
  const [comicData, setComicData] = useState<IComic>();
  console.log(comic);

  useEffect(() => {
    const id = parseInt(comic as string);

    if (comic) {
      getComicsById(id).then((data) => {
        setComicData(data);
        console.log(data);
      });
    }
  }, [comic]);

  if (!comic) {
    return (
      <>
        <CircularProgress />
      </>
    );
  }

  return (
    <Box
      sx={{
        padding: { xs: "80px 20px", sm: "100px 20px" },
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        direction={{ sm: "column", md: "row-reverse" }}
        spacing={{ xs: 15, sm: 15, md: 15 }}
        alignItems={{ xs: "center", sm: "center", md: "self-start" }}
      >
        <CardCheckoutProduct comic={comicData} />
        <Box>
          <StepperForm />
        </Box>
      </Stack>
    </Box>
  );
};
(Checkout as any).Layout = LayoutCheckout;

export default Checkout;
